[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_staking = "J7jh3C4HkTjWd71DqMxaZLohLJezDEXkm78A73nYjhRe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
