[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "96bRMHrgwi46MG21PxNJF7v4xww75hfkmU8QbWNXrqh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
